// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeRKrEUvUDCPFDQSwAnSc-ORWV_5vmr44',
    appId: '1:703522963799:web:72e628cc575c1d03a8be12',
    messagingSenderId: '703522963799',
    projectId: 'language-learning-app-45b70',
    authDomain: 'language-learning-app-45b70.firebaseapp.com',
    storageBucket: 'language-learning-app-45b70.firebasestorage.app',
    measurementId: 'G-224S7XQ2ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuDbVeXu6Yb-Ryh6JxrhJPM_yDjH51LI',
    appId: '1:703522963799:android:116c8173d7a6cc2fa8be12',
    messagingSenderId: '703522963799',
    projectId: 'language-learning-app-45b70',
    storageBucket: 'language-learning-app-45b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkc_PX3_LYktTOIcnPbziZ9pmasTsDf9k',
    appId: '1:703522963799:ios:ee9c6f4f4d8b147fa8be12',
    messagingSenderId: '703522963799',
    projectId: 'language-learning-app-45b70',
    storageBucket: 'language-learning-app-45b70.firebasestorage.app',
    iosBundleId: 'com.app.konnected',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkc_PX3_LYktTOIcnPbziZ9pmasTsDf9k',
    appId: '1:703522963799:ios:ee9c6f4f4d8b147fa8be12',
    messagingSenderId: '703522963799',
    projectId: 'language-learning-app-45b70',
    storageBucket: 'language-learning-app-45b70.firebasestorage.app',
    iosBundleId: 'com.app.konnected',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeRKrEUvUDCPFDQSwAnSc-ORWV_5vmr44',
    appId: '1:703522963799:web:e7e72f6155586ca0a8be12',
    messagingSenderId: '703522963799',
    projectId: 'language-learning-app-45b70',
    authDomain: 'language-learning-app-45b70.firebaseapp.com',
    storageBucket: 'language-learning-app-45b70.firebasestorage.app',
    measurementId: 'G-TTRZDY48EX',
  );
}
