enum AppLanguage { english, korean }

class ConstString {
  ConstString._();

  static const Map<String, String> _en = {
    'appName': 'Konnected',
    'tagline': 'Connect. Learn. Grow.',
    'findTutor': 'Find a Tutor',
    'findTutorSubtitle': 'Learn from peers across the globe',
    'becomeTutor': 'Become a Tutor',
    'becomeTutorSubtitle': 'Share your knowledge and language',
    'welcomeBack': 'Welcome Back',
    'createAccount': 'Create Account',
    'email': 'Email',
    'enterOtpError': 'Please enter OTP',
    'schoolEmail': 'School Email',
    'emailOtpOnly': 'Use email OTP. No password required.',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password?',
    'login': 'Login',
    'enterShortBioError': 'Please enter short bio',
    'enterTopicError': 'Please enter at least one topic',
    'signup': 'Sign Up',
    'dontHaveAccount': "Don't have an account? Sign Up",
    'alreadyHaveAccount': 'Already have an account? Login',
    'continueGoogle': 'Continue with Google',
    'or': 'or',
    'invalidEmail': 'Please enter a valid email address',
    'selectCountryError': 'Please select country',
    'enterEmailAddressError': 'Please enter email address',
    'selectBirthYearError': 'Please select birth year',
    'wrongPassword': 'Password must be at least 8 characters',
    'country': 'Country',
    'unitedStates': 'United States',
    'southKorea': 'South Korea',
    'terms': 'I agree to Terms & Privacy Policy',
    'usEduRule': 'US users must use an .edu email address',
    'krDomainRule': 'Korean users cannot use personal email domains',
    'otpTitle': 'OTP Verification',
    'otpSubtitle': "We've sent a 6-digit code to your email",
    'resendCode': 'Resend code',
    'verify': 'Verify',
    'sendOtp': 'Send OTP',
    'otpSentTo': 'OTP sent to',
    'ageTitle': 'Age Verification',
    'ageRule': 'Only users aged 14–17 can continue',
    'birthYear': 'Birth Year',
    'continue': 'Continue',
    'profileTitle': 'Complete Profile',
    'profileIncomplete': 'Your Profile is incomplete. Please complete your profile.',
    'displayName': 'Display Name',
    'headline': 'Headline',
    'enterHeadlineError': 'Please enter headline',
    'enterHeadlineErrorLength': 'Headline must be at least 10 characters',
    'enterShortBioErrorLength': 'Short bio must be at least 50 characters',
    'timezone': 'Timezone',
    'primaryLanguage': 'Primary Language',
    'targetLanguage': 'Target Language',
    'primaryTaught': 'Primary Taught',
    'targetSpoken': 'Target Spoken',
    'interests': 'Interests',
    'shortBio': 'Short Bio',
    'english': 'English',
    'korean': '한국어',
    'enterDisplayNameError': 'Please enter display name',
    'selectTimezoneError': 'Please select timezone',
    'selectPrimaryLanguageError': 'Please select primary language',
    'selectTargetLanguageError': 'Please select target language',
    'selectPrimaryTaughtError': 'Please select primary taught',
    'selectTargetSpokenError': 'Please select target spoken',
    'selectInterestsError': 'Please select interests',

    // Shared UI (student/tutor dashboards)
    'hi': 'Hi',
    'tutorSpeakPrimaryLanguage': 'Tutor speak my Primary language',
    'yes': 'YES',
    'no': 'NO',
    'searchTutors': 'Search tutors...',
    'recommendedTutors': 'Recommended Tutors',
    'noTutorsMatch': 'No tutors match your filter.',
    'filter': 'Filter',
    'clear': 'Clear',
    'noSlotsFound': 'No slots found',
    'deleteSlotTitle': 'Delete Slot',
    'deleteSlotConfirmMessage':
        'Are you sure you want to delete this slot?',
    'deleteSuccess': 'Slot deleted successfully',
    'availabilitySlot': 'Availability slot',
    'cancel': 'Cancel',
    'apply': 'Apply',
    'primary': 'Primary',
    'target': 'Target',
    'secondary': 'Secondary',
    'next': 'Next',
    'book': 'Book',
    'checkAvailability': 'Check Availability',
    'bookSession': 'Book Session',

    'sessions': 'Sessions',
    'upcoming': 'Upcoming',
    'complete': 'Complete',
    'current': 'Current',
    'past': 'Past',
    'remaining': 'Remaining',
    'join': 'Join',
    'upcomingSessionsTitle': 'Upcoming Sessions',

    'settings': 'Settings',
    'profile': 'Profile',
    'termsAndConditions': 'Terms and Conditions',
    'privacyPolicy': 'Privacy Policy',
    'review': 'Review',
    'language': 'Language',
    'logout': 'LOGOUT',

    'editProfile': 'Edit your profile',
    'bio': 'Bio',
    'save': 'Save',

    'booking': 'Booking',
    'tutorDetails': 'Tutor Details',
    'selectSlot': 'Select Slot',
    'selectTopic': 'Select Topic',
    'calendarView': 'Calendar view',
    'noSlotsAvailable': 'No slots available.',
    'noSlotsAvailableTutor': 'No slots available',
    'showInCalendarView': 'Show in calendar view',
    'sessionGoal': 'Session Goal',
    'optionalNote': 'Optional Note',
    'optionalNoteHint': 'Tell your tutor what you want to practice...',
    'bioHint': 'Write a short introduction...',
    'confirmBooking': 'Confirm booking',
    'cancellationPolicy':
        'Cancellation Policy: You can cancel up to 30 minutes before the session starts.',

    'conversation': 'Conversation',
    'pronunciation': 'Pronunciation',
    'homeworkHelp': 'Homework Help',
    'culture': 'Culture',

    'liveSession': 'Live Session',
    'report': 'Report',
    'block': 'Block',
    'endSession': 'End Session',

    // Tutor side
    'createProfile': 'Create Profile',
    'dashboard': 'Dashboard',
    'availability': 'Availability',
    'sessionsTab': 'Sessions',
    'tutorSettings': 'Tutor Settings',
    'tutorSessions': 'Tutor Sessions',
    'welcomeTutor': 'Welcome Tutor',
    'todaySessions': "Today's Sessions",
    'sessionsToday': 'Sessions Today',
    'upcomingSessions': 'Upcoming Sessions',
    'earnings': 'Earnings',
    'upcomingBookings': 'Upcoming Bookings',
    'date': 'Date',
    'time': 'Time',
    'durationMin': 'Duration (Min)',
    'status': 'Status',
    'month': 'Month',
    'availabilityCalendarTitle': 'Availability',
    'dateWiseAvailabilityData': 'Date-wise Availability Data',
    'noDataOnDate': 'No data on this date.',
    'noData' : 'No data',
    'availableStatus': 'Available',
    'busyStatus': 'Busy',
    'topic': 'Topic',
    'tutorHeadline': 'Tutor Headline',
    'submit': 'Submit',
    'viewPublicListingPreview': 'View Public Listing Preview',
    'addSlot': 'Add Slot',
    'weeklyCalendar': 'Weekly Calendar',
    'thirtyMinuteSlots': '30-minute Slots',
    'availableSlotsTitle': 'Available Slots',
    'addSlotDetails': 'Add slot details',
    'topics': 'Topics',
    'startTime': 'Start Time',
    'endTime': 'End Time',
    'shortDescription': 'Short Description',
    'shortDescriptionHint': 'Write a short description...',
    'selectDateError': 'Please select a date',
    'selectStartTimeError': 'Please select start time',
    'selectEndTimeError': 'Please select end time',
    'enterShortDescriptionError': 'Please enter short description',
    'invalidTimeRangeError': 'End time must be after start time',
    'selectTopicError': 'Please select topic',
    'selectSlotError': 'Please select slot',
    'bookingSuccess': 'Booking confirmed',
    'cancelSessionConfirmTitle': 'Cancel Session',
    'cancelSessionConfirmMessage': 'Are you sure you want to cancel this session?',
    'reportSpam': 'Report / Review',
    'reportSessionTitle': 'Report this session',
    'reportList': 'Report / Review List',
    'reportListEmpty': 'No reports found.',
    'reportReason': 'Reason',
    'reportSessionId': 'Session ID',
    'reportedOn': 'Reported On',
    'reportSessionReasonHint':
        'Describe what happened. Your report helps keep the community safe.',
    'reportSessionReasonEmptyError': 'Please enter a reason for your report.',
    'reportSessionSuccessFallback': 'Report submitted successfully',
    'createTutorProfile': 'Create Tutor Profile',
    'publishedListingPreview': 'Published Listing Preview',
    'publish': 'Publish',
    'unpublish': 'Unpublish',

    // Extra languages for dropdowns
    'spanish': 'Spanish',
    'japanese': 'Japanese',

    'noInternetMessage':
        'No internet connection. Check Wi‑Fi or mobile data.',
  };

  static const Map<String, String> _ko = {
    'appName': '코넥티드',
    'tagline': '연결하고. 배우고. 성장하세요.',
    'findTutor': '튜터 찾기',
    'findTutorSubtitle': '전 세계의 동료들과 함께 배워요',
    'becomeTutor': '튜터 되기',
    'becomeTutorSubtitle': '지식과 언어를 공유해요',
    'welcomeBack': '다시 오신 것을 환영합니다',
    'createAccount': '계정 만들기',
    'email': '이메일',
    'enterOtpError': 'OTP를 입력해 주세요',
    'schoolEmail': '학교 이메일',
    'emailOtpOnly': '이메일 OTP로 로그인/가입하세요. 비밀번호는 필요하지 않습니다.',
    'password': '비밀번호',
    'confirmPassword': '비밀번호 확인',
    'forgotPassword': '비밀번호를 잊으셨나요?',
    'login': '로그인',
    'signup': '회원가입',
    'dontHaveAccount': '계정이 없으신가요? 회원가입',
    'alreadyHaveAccount': '이미 계정이 있으신가요? 로그인',
    'continueGoogle': 'Google로 계속하기',
    'or': '또는',
    'primaryTaught': '기본 교육 언어',
    'targetSpoken': '목표 발화 언어',
    'invalidEmail': '올바른 이메일 주소를 입력해 주세요',
    'enterTopicError': '최소 한 개의 주제를 입력해 주세요',
    'selectCountryError': '국가를 선택해 주세요',
    'enterEmailAddressError': '이메일 주소를 입력해 주세요',
    'selectBirthYearError': '출생 연도를 선택해 주세요',
    'wrongPassword': '비밀번호는 최소 8자 이상이어야 합니다',
    'country': '국가',
    'unitedStates': '미국',
    'southKorea': '대한민국',
    'terms': '약관 및 개인정보 처리방침에 동의합니다',
    'usEduRule': '미국 사용자는 .edu 이메일을 사용해야 합니다',
    'krDomainRule': '한국 사용자는 개인 이메일 도메인을 사용할 수 없습니다',
    'otpTitle': 'OTP 인증',
    'otpSubtitle': '이메일로 전송된 6자리 코드를 입력하세요',
    'resendCode': '코드 재전송',
    'verify': '인증하기',
    'sendOtp': 'OTP 보내기',
    'otpSentTo': 'OTP 전송 대상',
    'ageTitle': '나이 인증',
    'ageRule': '14~17세 사용자만 계속할 수 있습니다',
    'birthYear': '출생 연도',
    'continue': '계속하기',
    'profileTitle': '프로필 완성',
    'displayName': '표시 이름',
    'timezone': '시간대',
    'primaryLanguage': '모국어',
    'targetLanguage': '학습 언어',
    'interests': '관심사',
    'shortBio': '짧은 자기소개',
    'english': 'English',
    'korean': '한국어',
    'enterDisplayNameError': '표시 이름을 입력해 주세요',
    'selectTimezoneError': '시간대를 선택해 주세요',
    'selectPrimaryLanguageError': '모국어를 선택해 주세요',
    'selectTargetLanguageError': '학습 언어를 선택해 주세요',
    'selectInterestsError': '관심사를 선택해 주세요',
    'selectPrimaryTaughtError': '기본 교육 언어를 선택해 주세요',
    'selectTargetSpokenError': '목표 발화 언어를 선택해 주세요',

    // Shared UI (student/tutor dashboards)
    'hi': '안녕하세요',
    'tutorSpeakPrimaryLanguage': '튜터가 제 기본 언어로 말하기',
    'no': '아니오',
    'searchTutors': '튜터 검색...',
    'recommendedTutors': '추천 튜터',
    'noTutorsMatch': '필터에 맞는 튜터가 없습니다(임시).',
    'profileIncomplete': '프로필이 완료되지 않았습니다. 프로필을 완료해주세요.',
    'filter': '필터',
    'clear': '초기화',
    'noSlotsFound': '슬롯이 없습니다',
    'deleteSlotTitle': '슬롯 삭제',
    'deleteSlotConfirmMessage': '이 슬롯을 삭제하시겠습니까?',
    'deleteSuccess': '슬롯이 삭제되었습니다',
    'headline': '헤드라인',
    'availabilitySlot': '이용 가능 시간',
    'cancel': '취소',
    'apply': '적용',
    'primary': '기본',
    'target': '목표',
    'secondary': '보조',
    'next': '다음',
    'book': '예약',
    'checkAvailability': '예약 가능 시간 확인',
    'bookSession': '세션 예약',
    'enterShortBioError': '짧은 자기소개를 입력해 주세요',

    'sessions': '세션',
    'upcoming': '예정',
    'current': '현재',
    'past': '지난',
    'join': '참여',

    'complete': '완료',
    'remaining': '남은',
    'upcomingSessionsTitle': '예정 세션',

    'settings': '설정',
    'profile': '프로필',
    'termsAndConditions': '이용 약관 및 개인정보 처리방침',
    'noSlotsAvailableTutor': '사용 가능한 시간이 없습니다',
    'privacyPolicy': '개인정보 처리방침',
    'review': '후기',
    'language': '언어',
    'logout': '로그아웃',
    'enterHeadlineError': '헤드라인을 입력해 주세요',

    'editProfile': '프로필 수정',
    'bio': '소개',
    'save': '저장',

    'booking': '예약',
    'tutorDetails': '튜터 정보',
    'selectSlot': '시간 선택',
    'selectTopic': '주제 선택',
    'calendarView': '캘린더 보기',
    'noSlotsAvailable': '사용 가능한 시간이 없습니다(임시).',
    'showInCalendarView': '캘린더에 표시',
    'sessionGoal': '세션 목표',
    'optionalNote': '추가 메모',
    'optionalNoteHint': '무엇을 연습하고 싶은지 튜터에게 알려주세요...',
    'bioHint': '짧은 자기소개를 작성해 주세요...',
    'confirmBooking': '예약 확인',
    'cancellationPolicy': '세션 시작 30분 전까지 취소하실 수 있습니다.',

    'conversation': '대화',
    'pronunciation': '발음',
    'homeworkHelp': '숙제 도움',
    'culture': '문화',

    'liveSession': '라이브 세션',
    'report': '신고',
    'block': '차단',
    'endSession': '세션 종료',
    'enterHeadlineErrorLength': '헤드라인은 최소 10자 이상이어야 합니다',

    // Tutor side
    'createProfile': '프로필 생성',
    'dashboard': '대시보드',
    'availability': '가능 시간',
    'sessionsTab': '세션',
    'tutorSettings': '튜터 설정',
    'tutorSessions': '튜터 세션',
    'welcomeTutor': '튜터님 환영합니다',
    'todaySessions': "오늘의 세션",
    'noData' : '데이터가 없습니다',
    'earnings': '수익',
    'upcomingBookings': '다가오는 예약',
    'date': '날짜',
    'time': '시간',
    'durationMin': '소요 시간(분)',
    'status': '상태',
    'month': '월',
    'availabilityCalendarTitle': '가능 시간',
    'dateWiseAvailabilityData': '날짜별 가능 시간 데이터',
    'noDataOnDate': '해당 날짜에 데이터가 없습니다.',
    'availableStatus': '예약 가능',
    'busyStatus': '예약 불가',
    'enterShortBioErrorLength': '짧은 자기소개는 최소 50자 이상이어야 합니다',
    'topic': '주제',
    'tutorHeadline': '튜터 헤드라인',
    'submit': '제출',
    'viewPublicListingPreview': '공개 목록 미리보기 보기',
    'addSlot': '시간 추가',
    'weeklyCalendar': '주간 캘린더',
    'thirtyMinuteSlots': '30분 슬롯',
    'availableSlotsTitle': '사용 가능 시간',
    'addSlotDetails': '슬롯 상세 입력',
    'topics': '주제',
    'startTime': '시작 시간',
    'endTime': '종료 시간',
    'shortDescription': '짧은 설명',
    'shortDescriptionHint': '짧은 설명을 작성해 주세요...',
    'selectDateError': '날짜를 선택해 주세요',
    'selectStartTimeError': '시작 시간을 선택해 주세요',
    'selectEndTimeError': '종료 시간을 선택해 주세요',
    'enterShortDescriptionError': '짧은 설명을 입력해 주세요',
    'invalidTimeRangeError': '종료 시간은 시작 시간보다 늦어야 합니다',
    'selectTopicError': '주제를 선택해 주세요',
    'selectSlotError': '시간을 선택해 주세요',
    'bookingSuccess': '예약이 완료되었습니다',
    'cancelSessionConfirmTitle': '세션 취소',
    'cancelSessionConfirmMessage': '이 세션을 취소하시겠습니까?',
    'reportSpam': '신고 / 검토',
    'reportSessionTitle': '이 세션 신고',
    'reportList': '신고 내역',
    'reportListEmpty': '신고 내역이 없습니다.',
    'reportReason': '사유',
    'reportSessionId': '세션 ID',
    'reportedOn': '신고일',
    'reportSessionReasonHint':
        '어떤 일이 있었는지 알려주세요. 커뮤니티 안전에 도움이 됩니다.',
    'reportSessionReasonEmptyError': '신고 사유를 입력해 주세요.',
    'reportSessionSuccessFallback': '신고가 접수되었습니다',
    'yes': '예',
    'createTutorProfile': '튜터 프로필 생성',
    'publishedListingPreview': '공개 목록 미리보기',
    'publish': '게시',
    'unpublish': '게시 중지',

    // Extra languages for dropdowns
    'spanish': '스페인어',
    'japanese': '일본어',

    'noInternetMessage': '인터넷에 연결되어 있지 않습니다. Wi‑Fi 또는 모바일 데이터를 확인해 주세요.',
  };

  static String text(AppLanguage language, String key) {
    return language == AppLanguage.korean ? _ko[key] ?? key : _en[key] ?? key;
  }
}
