enum AppLanguage { english, korean, spanish }

class ConstString {
  ConstString._();

  static const Map<String, String> _en = {
    'appName': 'Konnected',
    'tagline': 'Connect. Learn. Grow.',
    'findTutor': 'Find a Tutor',
    'findTutorSubtitle': 'Learn from peers across the globe',
    'becomeTutor': 'Become a Tutor',
    'becomeTutorSubtitle': 'Share your knowledge and language',
    'welcomeBack': 'Welcome Back',
    'createAccount': 'Create Account',
    'selectProfilePictureError': 'Please select profile picture',
    'email': 'Email',
    'enterOtpError': 'Please enter OTP',
    'schoolEmail': 'School Email',
    'emailOtpOnly': 'Use email OTP. No password required.',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password?',
    'login': 'Login',
    'skipLogin': 'Skip',
    'enterShortBioError': 'Please enter short bio',
    'enterTopicError': 'Please enter at least one topic',
    'signup': 'Sign Up',
    'dontHaveAccount': "Don't have an account? Sign Up",
    'alreadyHaveAccount': 'Already have an account? Login',
    'continueGoogle': 'Continue with Google',
    'or': 'or',
    'invalidEmail': 'Please enter a valid email address',
    'selectCountryError': 'Please select country',
    'selectBirthYear': 'Select Birth Year',
    'selectCountry': 'Select Country',
    'enterEmail': 'Enter Email',
    'enterEmailAddressError': 'Please enter email address',
    'selectBirthYearError': 'Please select birth year',
    'wrongPassword': 'Password must be at least 8 characters',
    'country': 'Country',
    'unitedStates': 'United States',
    'southKorea': 'South Korea',
    'spain': 'Spain',
    'terms': 'I agree to Terms & Privacy Policy',
    'usEduRule': 'US users must use an .edu email address',
    'krDomainRule': 'Korean users must use an .ac.kr & .school.kr email address',
    'esDomainRule': 'Spanish users must use an .es email address',
    'otpTitle': 'OTP Verification',
    'otpSubtitle': "We've sent a 6-digit code to your email",
    'resendCode': 'Resend code',
    'verify': 'Verify',
    'sendOtp': 'Send OTP',
    'otpSentTo': 'OTP sent to',
    'otpResentSuccess': 'A new code has been sent to your email.',
    'ageTitle': 'Age Verification',
    'ageRule': 'Only users aged 14–17 can continue',
    'tutorBirthYearRule':
        'Select your birth year. Years from 1900 through the current year are listed.',
    'birthYear': 'Birth Year',
    'continue': 'Continue',
    'profileTitle': 'Complete Profile',
    'profilePhotoGuidelinesTitle': 'What your photo needs',
    'profilePhotoGuidelineFacingForward': 'You should be facing forward',
    'profilePhotoGuidelineHeadShoulders': 'Frame your head and shoulders',
    'profilePhotoGuidelineCenteredUpright':
        'You should be centered and upright',
    'profilePhotoGuidelineFaceVisible':
        'Your face and eyes should be visible',
    'profilePhotoGuidelineOnlyPerson':
        'You should be the only person in the photo',
    'profilePhotoGuidelineColorHighRes':
        'Use a color photo with high resolution and no filters',
    'profilePhotoGuidelineNoLogos':
        'Avoid logos or contact information',
    'profileIncomplete':
        'Your Profile is incomplete. Please complete your profile.',
    'displayName': 'Display Name',
    'headline': 'Headline',
    'enterHeadlineError': 'Please enter headline',
    'enterHeadlineErrorLength': 'Headline must be at least 10 characters',
    // 'enterShortBioErrorLength': 'Short bio must be at least 50 characters',
    'timezone': 'Timezone',
    'timezoneLockedProfileHint':
        'Your timezone was saved when you first signed in and cannot be changed here.',
    'primaryLanguage': 'Subject you teach',
    'yourPrimaryLanguage': 'Your Primary Language',
    'targetLanguage': 'Target Language',
    'primaryTaught': 'Primary Language',
    'targetSpoken': 'Language fluency',
    'languageFluency': 'Languages you speak',
    'interests': 'Interests',
    'shortBio': 'Short Bio',
    'english': 'English',
    'korean': '한국어',
    'enterDisplayNameError': 'Please enter display name',
    'selectTimezoneError': 'Please select timezone',
    'selectPrimaryLanguageError': 'Please select subject you teach',
    'selectTargetLanguageError': 'Please select target language',
    'selectPrimaryTaughtError': 'Please select primary taught',
    'selectTargetSpokenError': 'Please select target spoken',
    'selectLanguageFluencyError': 'Please select Languages you speak',
    'selectInterestsError': 'Please select interests',

    // Shared UI (student/tutor dashboards)
    'hi': 'Hi',
    'guestVisitor': 'there',
    'signInRequiredTitle': 'Sign in required',
    'signInRequiredMessage':
        'Log in or create an account to book a session with this tutor.',
    'signInRequiredMessageChat':
        'Log in or create an account to message this tutor.',
    'chatUnableToOpen':
        'Unable to open chat right now. Please log out and sign in again, then try again.',
    'tutorSpeakPrimaryLanguage': 'Tutor speak my Primary language',
    'yes': 'YES',
    'no': 'NO',
    'searchTutors': 'Search tutors...',
    'searchStudentBookings': 'Search by student name...',
    'allDates': 'All dates',
    'recommendedTutors': 'Recommended Tutors',
    'allTutors': 'All',
    'favoriteTutors': 'Favorites',
    'noFavoriteTutors': 'No favorite tutors yet. Tap the heart on a tutor to save them.',
    'noTutorsMatch': 'No tutors match your filter.',
    'filter': 'Filter',
    'clear': 'Clear',
    'noSlotsFound': 'No slots found',
    'deleteSlotTitle': 'Delete Slot',
    'deleteSlotConfirmMessage': 'Are you sure you want to delete this slot?',
    'delete': 'Delete',
    'deleteSuccess': 'Slot deleted successfully',
    'availabilitySlot': 'Availability slot',
    'cancel': 'Cancel',
    'done': 'Done',
    'apply': 'Apply',
    'primary': 'Primary',
    'target': 'Target',
    'secondary': 'Secondary',
    'next': 'Next',
    'book': 'Book',
    'checkAvailability': 'Check Availability',
    'bookSession': 'Book Session',

    'sessions': 'Sessions',
    'upcoming': 'Upcoming',
    'today': 'Today',
    'complete': 'Complete',
    'current': 'Current',
    'past': 'Past',
    'remaining': 'Remaining',
    'join': 'Join',
    'upcomingSessionsTitle': 'Upcoming Sessions',
    'isPublished': 'Do you want to publish your profile?',

    'settings': 'Settings',
    'profile': 'Profile',
    'termsAndConditions': 'Terms and Conditions',
    'privacyPolicy': 'Privacy Policy',
    'review': 'Review',
    'language': 'Language',
    'logout': 'LOGOUT',
    'deleteAccount': 'Delete Account',
    'deleteAccountTitle': 'Delete Account',
    'deleteAccountSubtitle':
        'Tell us why you are leaving. Your account and data will be permanently removed.',
    'deleteAccountReasonLabel': 'Reason for leaving',
    'deleteAccountReasonHint': 'Please share why you want to delete your account...',
    'enterDeleteReasonError': 'Please enter a reason before continuing',
    'enterDeleteReasonErrorLength': 'Reason must be at least 10 characters',
    'deleteAccountWarning':
        'This action is permanent. Your profile, bookings, and session history etc... will be removed.',
    'deleteAccountConfirmTitle': 'Delete account?',
    'deleteAccountConfirmMessage':
        'Your account and all associated data will be permanently deleted. This cannot be undone.',
    'deleteAccountSuccessTitle': 'Account deleted',
    'deleteAccountSuccessMessage':
        'Your account has been permanently deleted.',

    'editProfile': 'Edit your profile',
    'bio': 'Bio',
    'save': 'Save',

    'booking': 'Booking',
    'tutorDetails': 'Tutor Details',
    'selectSlot': 'Select Slot',
    'selectTopic': 'Select Topic',
    'calendarView': 'Calendar view',
    'noSlotsAvailable': 'No slots available.',
    'noSlotsAvailableTutor': 'No slots available',
    'showInCalendarView': 'Show in calendar view',
    'sessionGoal': 'Session Goal',
    'optionalNote': 'Optional Note',
    'optionalNoteHint': 'Tell your tutor what you want to practice...',
    'bioHint': 'Write a short introduction...',
    'confirmBooking': 'Confirm booking',
    'cancellationPolicy':
        'Cancellation Policy: You can cancel up to 30 minutes before the session starts.',

    'conversation': 'Conversation',
    'pronunciation': 'Pronunciation',
    'homeworkHelp': 'Homework Help',
    'culture': 'Culture',

    'liveSession': 'Live Session',
    'report': 'Report',
    'block': 'Block',
    'endSession': 'End Session',

    // Tutor side
    'createProfile': 'Create Profile',
    'dashboard': 'Dashboard',
    'availability': 'Availability',
    'sessionsTab': 'Sessions',
    'tutorSettings': 'Tutor Settings',
    'tutorSessions': 'Tutor Sessions',
    'welcomeTutor': 'Welcome Tutor',
    'todaySessions': "Today's Sessions",
    'sessionsToday': 'Sessions Today',
    'upcomingSessions': 'Upcoming Sessions',
    'earnings': 'Earnings',
    'upcomingBookings': 'Upcoming Bookings',
    'date': 'Date',
    'time': 'Time',
    'durationMin': 'Duration (Min)',
    'status': 'Status',
    'month': 'Month',
    'availabilityCalendarTitle': 'Availability',
    'dateWiseAvailabilityData': 'Date-wise Availability Data',
    'noDataOnDate': 'No data on this date.',
    'noData': 'No data',
    'availableStatus': 'Available',
    'busyStatus': 'Busy',
    'topic': 'Topic',
    'seeMore': 'See more',
    'seeLess': 'See less',
    'tutorHeadline': 'Tutor Headline',
    'submit': 'Submit',
    'viewPublicListingPreview': 'View Public Listing Preview',
    'addSlot': 'Add Slot',
    'editSlot': 'Edit Slot',
    'edit': 'Edit',
    'slotBooked': 'Booked',
    'weeklyCalendar': 'Weekly Calendar',
    'thirtyMinuteSlots': '30-minute Slots',
    'availableSlotsTitle': 'Available Slots',
    'addSlotDetails': 'Add slot details',
    'topics': 'Topics',
    'startTime': 'Start Time',
    'endTime': 'End Time',
    'shortDescription': 'Short Description',
    'shortDescriptionHint': 'Write a short description...',
    'selectDate': 'Select Date',
    'selectDateError': 'Please select a date',
    'selectStartTimeError': 'Please select start time',
    'selectEndTimeError': 'Please select end time',
    'enterShortDescriptionError': 'Please enter short description',
    'invalidTimeRangeError': 'End time must be after start time',
    'timeIntervalFiveError':
        'End time must be at least 5 minutes after start time and in 5-minute intervals',
    'selectTopicError': 'Please select topic',
    'selectSlotError': 'Please select slot',
    'bookingSuccess': 'Booking confirmed',
    'cancelSessionConfirmTitle': 'Cancel Session',
    'cancelSessionConfirmMessage':
        'Are you sure you want to cancel this session?',
    'reportSpam': 'Report / Review',
    'reportSessionTitle': 'Report this session',
    'message': 'Message',
    'chat': 'Chat',
    'chatWithTutor': 'Tutor chat',
    'chatWithStudent': 'Student chat',
    'typeMessage': 'Type a message...',
    'chatEmptyTitle': 'Start the conversation',
    'chatEmptySubtitle': 'Send a message to {name} to coordinate your session.',
    'chatInboxEmptyTitle': 'No chats yet',
    'chatInboxEmptySubtitle':
        'When students message you, conversations will appear here.',
    'chatNoMessagesYet': 'No messages yet',
    'notifications': 'Notifications',
    'notificationsEmpty': 'No notifications yet.',
    'notificationSessionStart': 'Session start',
    'notificationSessionCancel': 'Session cancel',
    'reportList': 'Report / Review List',
    'reportListEmpty': 'No reports found.',
    'reportReason': 'Reason',
    'reportSessionId': 'Session ID',
    'reportedOn': 'Reported On',
    'reportSessionReasonHint':
        'Describe what happened. Your report helps keep the community safe.',
    'selectReportTypeHint': 'Select type',
    'reportSessionTypeEmptyError': 'Please select Report or Review.',
    'reportSessionReasonEmptyError': 'Please enter a reason for your report.',
    'sessionRatingLabel': 'Rate this session',
    'reportSessionRatingRequired':
        'Please choose a star rating for your review.',
    'reportSessionSuccessFallback': 'Report submitted successfully',
    'createTutorProfile': 'Create Tutor Profile',
    'publishedListingPreview': 'Published Listing Preview',
    'publish': 'Publish',
    'unpublish': 'Unpublish',

    // Extra languages for dropdowns
    'spanish': 'Spanish',
    'japanese': 'Japanese',
    'other': 'Other',

    'noInternetMessage': 'No internet connection. Check Wi‑Fi or mobile data.',
    'locationServicesDisabled': 'Location services are disabled.',
    'locationPermissionsDenied': 'Location permissions are denied.',
    'locationPermissionsPermanentlyDenied':
        'Location permission has been permanently denied. To join the session, please enable location access in your device settings.',
  };

  static const Map<String, String> _ko = {
    'appName': '코넥티드',
    'tagline': '연결하고. 배우고. 성장하세요.',
    'findTutor': '튜터 찾기',
    'findTutorSubtitle': '전 세계의 동료들과 함께 배워요',
    'becomeTutor': '튜터 되기',
    'becomeTutorSubtitle': '지식과 언어를 공유해요',
    'welcomeBack': '다시 오신 것을 환영합니다',
    'createAccount': '계정 만들기',
    'email': '이메일',
    'enterOtpError': 'OTP를 입력해 주세요',
    'schoolEmail': '학교 이메일',
    'emailOtpOnly': '이메일 OTP로 로그인/가입하세요. 비밀번호는 필요하지 않습니다.',
    'password': '비밀번호',
    'confirmPassword': '비밀번호 확인',
    'forgotPassword': '비밀번호를 잊으셨나요?',
    'login': '로그인',
    'skipLogin': '건너뛰기',
    'selectProfilePictureError': '프로필 사진을 선택해 주세요',
    'signup': '회원가입',
    'dontHaveAccount': '계정이 없으신가요? 회원가입',
    'alreadyHaveAccount': '이미 계정이 있으신가요? 로그인',
    'continueGoogle': 'Google로 계속하기',
    'or': '또는',
    'primaryTaught': '기본 언어',
    'targetSpoken': '언어 숙련도',
    'languageFluency': '언어 숙련도',
    'invalidEmail': '올바른 이메일 주소를 입력해 주세요',
    'enterTopicError': '최소 한 개의 주제를 입력해 주세요',
    'selectCountryError': '국가를 선택해 주세요',
    'enterEmailAddressError': '이메일 주소를 입력해 주세요',
    'selectBirthYearError': '출생 연도를 선택해 주세요',
    'wrongPassword': '비밀번호는 최소 8자 이상이어야 합니다',
    'country': '국가',
    'unitedStates': '미국',
    'southKorea': '대한민국',
    'spain': '스페인',
    'terms': '약관 및 개인정보 처리방침에 동의합니다',
    'usEduRule': '미국 사용자는 .edu 이메일을 사용해야 합니다',
    'krDomainRule': '한국 사용자는 .ac.kr & .school.kr 이메일을 사용해야 합니다',
    'esDomainRule': '스페인 사용자는 .es 이메일을 사용해야 합니다',
    
    'otpTitle': 'OTP 인증',
    'otpSubtitle': '이메일로 전송된 6자리 코드를 입력하세요',
    'resendCode': '코드 재전송',
    'verify': '인증하기',
    'sendOtp': 'OTP 보내기',
    'otpSentTo': 'OTP 전송 대상',
    'enterDeleteReasonErrorLength': '탈퇴 사유는 최소 10자 이상이어야 합니다',
    'otpResentSuccess': '새 인증 코드가 이메일로 전송되었습니다.',
    'ageTitle': '나이 인증',
    'ageRule': '14~17세 사용자만 계속할 수 있습니다',
    'tutorBirthYearRule': '출생 연도를 선택하세요. 1900년부터 올해까지의 연도가 표시됩니다.',
    'birthYear': '출생 연도',
    'continue': '계속하기',
    'profileTitle': '프로필 완성',
    'profilePhotoGuidelinesTitle': '프로필 사진 요구사항',
    'profilePhotoGuidelineFacingForward': '정면을 바라보아야 합니다',
    'profilePhotoGuidelineHeadShoulders':
        '머리와 어깨가 화면에 들어가도록 맞춰 주세요',
    'profilePhotoGuidelineCenteredUpright':
        '화면 중앙에 서 있고 바른 자세로 촬영해 주세요',
    'profilePhotoGuidelineFaceVisible':
        '(종교적 사유가 아니라면) 얼굴과 눈이 잘 보이도록 해 주세요',
    'profilePhotoGuidelineOnlyPerson': '사진에는 본인만 나와야 합니다',
    'profilePhotoGuidelineColorHighRes':
        '컬러, 고해상도, 필터를 쓰지 않은 사진을 사용해 주세요',
    'profilePhotoGuidelineNoLogos':
        '로고나 연락처 정보가 보이지 않게 해 주세요',
    'displayName': '표시 이름',
    'timezone': '시간대',
    'timezoneLockedProfileHint': '시간대는 처음 가입할 때 저장되었으며 여기서는 변경할 수 없습니다.',
    'primaryLanguage': '모국어',
    'yourPrimaryLanguage': '나의 모국어',
    'targetLanguage': '학습 언어',
    'interests': '관심사',
    'shortBio': '짧은 자기소개',
    'english': 'English',
    'korean': '한국어',
    'enterDisplayNameError': '표시 이름을 입력해 주세요',
    'selectTimezoneError': '시간대를 선택해 주세요',
    'selectPrimaryLanguageError': '모국어를 선택해 주세요',
    'selectTargetLanguageError': '학습 언어를 선택해 주세요',
    'selectInterestsError': '관심사를 선택해 주세요',
    'selectPrimaryTaughtError': '기본 교육 언어를 선택해 주세요',
    'enterEmail': '이메일 입력',
    'selectTargetSpokenError': '목표 발화 언어를 선택해 주세요',
    'selectLanguageFluencyError': '언어 숙련도를 선택해 주세요',

    // Shared UI (student/tutor dashboards)
    'hi': '안녕하세요',
    'guestVisitor': '방문자',
    'signInRequiredTitle': '로그인이 필요합니다',
    'signInRequiredMessage': '이 튜터와 수업을 예약하려면 로그인하거나 계정을 만드세요.',
    'signInRequiredMessageChat':
        '이 튜터에게 메시지를 내려면 로그인하거나 계정을 만드세요.',
    'chatUnableToOpen':
        '지금은 채팅을 열 수 없습니다. 로그아웃 후 다시 로그인한 뒤 시도해 주세요.',
    'tutorSpeakPrimaryLanguage': '튜터가 제 기본 언어로 말하기',
    'no': '아니오',
    'searchTutors': '튜터 검색...',
    'searchStudentBookings': '학생 이름으로 검색...',
    'allDates': '전체 날짜',
    'recommendedTutors': '추천 튜터',
    'allTutors': '전체',
    'favoriteTutors': '즐겨찾기',
    'noFavoriteTutors': '즐겨찾기한 튜터가 없습니다. 튜터의 하트를 눌러 저장하세요.',
    'noTutorsMatch': '필터에 맞는 튜터가 없습니다(임시).',
    'profileIncomplete': '프로필이 완료되지 않았습니다. 프로필을 완료해주세요.',
    'filter': '필터',
    'clear': '초기화',
    'noSlotsFound': '슬롯이 없습니다',
    'deleteSlotTitle': '슬롯 삭제',
    'deleteSlotConfirmMessage': '이 슬롯을 삭제하시겠습니까?',
    'delete': '삭제',
    'deleteSuccess': '슬롯이 삭제되었습니다',
    'headline': '헤드라인',
    'availabilitySlot': '이용 가능 시간',
    'cancel': '취소',
    'apply': '적용',
    'primary': '기본',
    'target': '목표',
    'secondary': '보조',
    'next': '다음',
    'book': '예약',
    'checkAvailability': '예약 가능 시간 확인',
    'bookSession': '세션 예약',
    'enterShortBioError': '짧은 자기소개를 입력해 주세요',

    'sessions': '세션',
    'upcoming': '예정',
    'today': '오늘',
    'current': '현재',
    'past': '지난',
    'join': '참여',

    'complete': '완료',
    'remaining': '남은',
    'upcomingSessionsTitle': '예정 세션',

    'settings': '설정',
    'profile': '프로필',
    'termsAndConditions': '이용 약관 및 개인정보 처리방침',
    'noSlotsAvailableTutor': '사용 가능한 시간이 없습니다',
    'privacyPolicy': '개인정보 처리방침',
    'review': '후기',
    'language': '언어',
    'logout': '로그아웃',
    'deleteAccount': '계정 삭제',
    'deleteAccountTitle': '계정 삭제',
    'deleteAccountSubtitle': '탈퇴 사유를 입력해 주세요. 계정과 데이터가 영구 삭제됩니다.',
    'deleteAccountReasonLabel': '탈퇴 사유',
    'deleteAccountReasonHint': '계정을 삭제하려는 이유를 입력해 주세요...',
    'enterDeleteReasonError': '계속하려면 사유를 입력해 주세요',
    'deleteAccountWarning':
        '이 작업은 되돌릴 수 없습니다. 프로필, 예약, 세션 기록이 모두 삭제됩니다.',
    'deleteAccountConfirmTitle': '계정을 삭제하시겠습니까?',
    'deleteAccountConfirmMessage':
        '계정과 모든 관련 데이터가 영구적으로 삭제됩니다. 이 작업은 취소할 수 없습니다.',
    'deleteAccountSuccessTitle': '계정이 삭제되었습니다',
    'deleteAccountSuccessMessage': '계정이 영구적으로 삭제되었습니다.',
    'enterHeadlineError': '헤드라인을 입력해 주세요',

    'editProfile': '프로필 수정',
    'bio': '소개',
    'save': '저장',

    'booking': '예약',
    'tutorDetails': '튜터 정보',
    'selectSlot': '시간 선택',
    'selectCountry': '국가 선택',
    'selectTopic': '주제 선택',
    'calendarView': '캘린더 보기',
    'noSlotsAvailable': '사용 가능한 시간이 없습니다(임시).',
    'showInCalendarView': '캘린더에 표시',
    'sessionGoal': '세션 목표',
    'optionalNote': '추가 메모',
    'optionalNoteHint': '무엇을 연습하고 싶은지 튜터에게 알려주세요...',
    'bioHint': '짧은 자기소개를 작성해 주세요...',
    'confirmBooking': '예약 확인',
    'cancellationPolicy': '세션 시작 30분 전까지 취소하실 수 있습니다.',

    'conversation': '대화',
    'pronunciation': '발음',
    'done': '완료',
    'homeworkHelp': '숙제 도움',
    'culture': '문화',

    'selectBirthYear': '출생 연도 선택',
    'liveSession': '라이브 세션',
    'report': '신고',
    'block': '차단',
    'endSession': '세션 종료',
    'enterHeadlineErrorLength': '헤드라인은 최소 10자 이상이어야 합니다',

    // Tutor side
    'createProfile': '프로필 생성',
    'dashboard': '대시보드',
    'availability': '가능 시간',
    'sessionsTab': '세션',
    'tutorSettings': '튜터 설정',
    'tutorSessions': '튜터 세션',
    'welcomeTutor': '튜터님 환영합니다',
    'todaySessions': "오늘의 세션",
    'noData': '데이터가 없습니다',
    'earnings': '수익',
    'upcomingBookings': '다가오는 예약',
    'date': '날짜',
    'time': '시간',
    'durationMin': '소요 시간(분)',
    'status': '상태',
    'month': '월',
    'availabilityCalendarTitle': '가능 시간',
    'dateWiseAvailabilityData': '날짜별 가능 시간 데이터',
    'noDataOnDate': '해당 날짜에 데이터가 없습니다.',
    'availableStatus': '예약 가능',
    'busyStatus': '예약 불가',
    // 'enterShortBioErrorLength': '짧은 자기소개는 최소 50자 이상이어야 합니다',
    'topic': '주제',
    'seeMore': '더 보기',
    'seeLess': '접기',
    'tutorHeadline': '튜터 헤드라인',
    'submit': '제출',
    'viewPublicListingPreview': '공개 목록 미리보기 보기',
    'addSlot': '시간 추가',
    'editSlot': '시간 수정',
    'edit': '수정',
    'slotBooked': '예약됨',
    'weeklyCalendar': '주간 캘린더',
    'thirtyMinuteSlots': '30분 슬롯',
    'availableSlotsTitle': '사용 가능 시간',
    'addSlotDetails': '슬롯 상세 입력',
    'topics': '주제',
    'startTime': '시작 시간',
    'endTime': '종료 시간',
    'shortDescription': '짧은 설명',
    'shortDescriptionHint': '짧은 설명을 작성해 주세요...',
    'selectDate': '날짜 선택',
    'selectDateError': '날짜를 선택해 주세요',
    'selectStartTimeError': '시작 시간을 선택해 주세요',
    'selectEndTimeError': '종료 시간을 선택해 주세요',
    'enterShortDescriptionError': '짧은 설명을 입력해 주세요',
    'invalidTimeRangeError': '종료 시간은 시작 시간보다 늦어야 합니다',
    'timeIntervalFiveError': '종료 시간은 시작 시간보다 최소 5분 이후이며 5분 단위여야 합니다',
    'selectTopicError': '주제를 선택해 주세요',
    'selectSlotError': '시간을 선택해 주세요',
    'bookingSuccess': '예약이 완료되었습니다',
    'cancelSessionConfirmTitle': '세션 취소',
    'cancelSessionConfirmMessage': '이 세션을 취소하시겠습니까?',
    'reportSpam': '신고 / 검토',
    'reportSessionTitle': '이 세션 신고',
    'message': '메시지',
    'chat': '채팅',
    'chatWithTutor': '튜터 채팅',
    'chatWithStudent': '학생 채팅',
    'typeMessage': '메시지를 입력하세요...',
    'chatEmptyTitle': '대화를 시작하세요',
    'chatEmptySubtitle': '{name}에게 메시지를 보내 세션을 조율하세요.',
    'chatInboxEmptyTitle': '채팅이 없습니다',
    'chatInboxEmptySubtitle': '학생이 메시지를 내면 여기에 대화가 표시됩니다.',
    'chatNoMessagesYet': '아직 메시지가 없습니다',
    'notifications': '알림',
    'notificationsEmpty': '알림이 없습니다.',
    'notificationSessionStart': '세션 시작',
    'notificationSessionCancel': '세션 취소',
    'reportList': '신고 내역',
    'reportListEmpty': '신고 내역이 없습니다.',
    'reportReason': '사유',
    'reportSessionId': '세션 ID',
    'reportedOn': '신고일',
    'reportSessionReasonHint': '어떤 일이 있었는지 알려주세요. 커뮤니티 안전에 도움이 됩니다.',
    'selectReportTypeHint': '유형 선택',
    'reportSessionTypeEmptyError': '신고 또는 후기를 선택해 주세요.',
    'reportSessionReasonEmptyError': '신고 사유를 입력해 주세요.',
    'sessionRatingLabel': '이 세션 평가',
    'reportSessionRatingRequired': '후기에는 별점을 선택해 주세요.',
    'reportSessionSuccessFallback': '신고가 접수되었습니다',
    'isPublished': '프로필을 공개하시겠습니까?',
    'yes': '예',
    'createTutorProfile': '튜터 프로필 생성',
    'publishedListingPreview': '공개 목록 미리보기',
    'publish': '게시',
    'unpublish': '게시 중지',

    // Extra languages for dropdowns
    'spanish': '스페인어',
    'japanese': '일본어',
    'other': '기타',

    'noInternetMessage': '인터넷에 연결되어 있지 않습니다. Wi‑Fi 또는 모바일 데이터를 확인해 주세요.',
    'locationServicesDisabled': '위치 서비스가 비활성화되어 있습니다.',
    'locationPermissionsDenied': '위치 권한이 거부되었습니다.',
    'locationPermissionsPermanentlyDenied':
        '위치 권한이 영구적으로 거부되었습니다. 세션에 참여하려면 기기 설정에서 위치 접근을 허용해 주십시오.',
  };

  static const Map<String, String> _es = {
    'appName': 'Konnected',
    'tagline': 'Conecta. Aprende. Crece.',
    'findTutor': 'Buscar Tutor',
    'findTutorSubtitle': 'Aprende de compañeros de todo el mundo',
    'becomeTutor': 'Ser Tutor',
    'becomeTutorSubtitle': 'Comparte tu conocimiento e idioma',
    'welcomeBack': 'Bienvenido de nuevo',
    'createAccount': 'Crear Cuenta',
    'email': 'Correo electrónico',
    'enterOtpError': 'Por favor ingresa el OTP',
    'schoolEmail': 'Correo escolar',
    'emailOtpOnly': 'Usa OTP por correo. No se requiere contraseña.',
    'password': 'Contraseña',
    'confirmPassword': 'Confirmar Contraseña',
    'forgotPassword': '¿Olvidaste tu contraseña?',
    'login': 'Iniciar Sesión',
    'skipLogin': 'Omitir',
    'enterShortBioError': 'Por favor ingresa una breve biografía',
    'enterTopicError': 'Por favor ingresa al menos un tema',
    'signup': 'Registrarse',
    'dontHaveAccount': '¿No tienes cuenta? Regístrate',
    'alreadyHaveAccount': '¿Ya tienes cuenta? Inicia sesión',
    'continueGoogle': 'Continuar con Google',
    'or': 'o',
    'invalidEmail': 'Por favor ingresa un correo electrónico válido',
    'selectCountryError': 'Por favor selecciona un país',
    'selectBirthYear': 'Seleccionar Año de Nacimiento',
    'selectCountry': 'Seleccionar País',
    'enterEmail': 'Ingresar Correo',
    'enterEmailAddressError': 'Por favor ingresa tu correo electrónico',
    'selectBirthYearError': 'Por favor selecciona el año de nacimiento',
    'wrongPassword': 'La contraseña debe tener al menos 8 caracteres',
    'country': 'País',
    'unitedStates': 'Estados Unidos',
    'southKorea': 'Corea del Sur',
    'spain': 'España',
    'terms': 'Acepto los Términos y Política de Privacidad',
    'usEduRule': 'Los usuarios de EE.UU. deben usar un correo .edu',
    'krDomainRule': 'Los usuarios coreanos deben usar un correo .ac.kr & .school.kr',
    'esDomainRule': 'Los usuarios españoles deben usar un correo .es',
    
    'otpTitle': 'Verificación OTP',
    'otpSubtitle': 'Te hemos enviado un código de 6 dígitos a tu correo',
    'resendCode': 'Reenviar código',
    'verify': 'Verificar',
    'sendOtp': 'Enviar OTP',
    'otpSentTo': 'OTP enviado a',
    'otpResentSuccess': 'Se ha enviado un nuevo código a tu correo.',
    'ageTitle': 'Verificación de Edad',
    'ageRule': 'Solo pueden continuar usuarios de 14 a 17 años',
    'tutorBirthYearRule':
        'Selecciona tu año de nacimiento. Se listan los años desde 1900 hasta el año actual.',
    'birthYear': 'Año de Nacimiento',
    'continue': 'Continuar',
    'profileTitle': 'Completar Perfil',
    'profilePhotoGuidelinesTitle': 'Qué debe tener tu foto',
    'profilePhotoGuidelineFacingForward': 'Debes mirar de frente',
    'profilePhotoGuidelineHeadShoulders': 'Encuadra cabeza y hombros',
    'profilePhotoGuidelineCenteredUpright':
        'Debes ir centrado y erguido',
    'profilePhotoGuidelineFaceVisible':
        'Tu cara y ojos deben verse',
    'profilePhotoGuidelineOnlyPerson':
        'Solo debes aparecer tú en la foto',
    'profilePhotoGuidelineColorHighRes':
        'Usa una foto a color, de alta resolución y sin filtros',
    'profilePhotoGuidelineNoLogos':
        'Evita logotipos o datos de contacto',
    'profileIncomplete':
        'Tu perfil está incompleto. Por favor completa tu perfil.',
    'displayName': 'Nombre de Pantalla',
    'headline': 'Titular',
    'enterHeadlineError': 'Por favor ingresa un titular',
    'enterHeadlineErrorLength': 'El titular debe tener al menos 10 caracteres',
    // 'enterShortBioErrorLength': 'La biografía corta debe tener al menos 50 caracteres',
    'timezone': 'Zona Horaria',
    'timezoneLockedProfileHint':
        'Tu zona horaria se guardó cuando iniciaste sesión por primera vez y no puede cambiarse aquí.',
    'primaryLanguage': 'Materia que enseñas',
    'yourPrimaryLanguage': 'Tu Idioma Principal',
    'targetLanguage': 'Idioma Objetivo',
    'primaryTaught': 'Idioma Principal',
    'targetSpoken': 'Fluidez en el idioma',
    'languageFluency': 'Idiomas que hablas',
    'interests': 'Intereses',
    'shortBio': 'Biografía Corta',
    'english': 'English',
    'korean': '한국어',
    'enterDisplayNameError': 'Por favor ingresa el nombre de pantalla',
    'selectTimezoneError': 'Por favor selecciona la zona horaria',
    'selectPrimaryLanguageError': 'Por favor selecciona la materia que enseñas',
    'selectTargetLanguageError': 'Por favor selecciona el idioma objetivo',
    'selectPrimaryTaughtError':
        'Por favor selecciona el idioma principal enseñado',
    'selectTargetSpokenError':
        'Por favor selecciona el idioma objetivo hablado',
    'selectLanguageFluencyError': 'Por favor selecciona los idiomas que hablas',
    'selectInterestsError': 'Por favor selecciona intereses',

    // Shared UI (student/tutor dashboards)
    'hi': 'Hola',
    'guestVisitor': 'visitante',
    'signInRequiredTitle': 'Inicio de sesión requerido',
    'signInRequiredMessage':
        'Inicia sesión o crea una cuenta para reservar una sesión con este tutor.',
    'signInRequiredMessageChat':
        'Inicia sesión o crea una cuenta para enviar un mensaje a este tutor.',
    'chatUnableToOpen':
        'No se puede abrir el chat ahora. Cierra sesión, vuelve a iniciar sesión e inténtalo de nuevo.',
    'tutorSpeakPrimaryLanguage': 'El tutor habla mi idioma principal',
    'yes': 'SÍ',
    'no': 'NO',
    'searchTutors': 'Buscar tutores...',
    'searchStudentBookings': 'Buscar por nombre del estudiante...',
    'allDates': 'Todas las fechas',
    'recommendedTutors': 'Tutores Recomendados',
    'allTutors': 'Todos',
    'favoriteTutors': 'Favoritos',
    'noFavoriteTutors':
        'Aún no tienes tutores favoritos. Toca el corazón en un tutor para guardarlo.',
    'noTutorsMatch': 'Ningún tutor coincide con tu filtro.',
    'filter': 'Filtrar',
    'clear': 'Limpiar',
    'noSlotsFound': 'No se encontraron horarios',
    'deleteSlotTitle': 'Eliminar Horario',
    'deleteSlotConfirmMessage':
        '¿Estás seguro de que quieres eliminar este horario?',
    'delete': 'Eliminar',
    'deleteSuccess': 'Horario eliminado correctamente',
    'availabilitySlot': 'Horario disponible',
    'cancel': 'Cancelar',
    'done': 'Listo',
    'apply': 'Aplicar',
    'primary': 'Principal',
    'target': 'Objetivo',
    'secondary': 'Secundario',
    'next': 'Siguiente',
    'book': 'Reservar',
    'selectProfilePictureError': 'Por favor selecciona una imagen de perfil',
    'checkAvailability': 'Ver Disponibilidad',
    'bookSession': 'Reservar Sesión',
    'enterDeleteReasonErrorLength': 'El motivo debe tener al menos 10 caracteres',

    'sessions': 'Sesiones',
    'upcoming': 'Próximas',
    'today': 'Hoy',
    'complete': 'Completada',
    'current': 'Actual',
    'past': 'Pasadas',
    'remaining': 'Restantes',
    'join': 'Unirse',
    'upcomingSessionsTitle': 'Próximas Sesiones',
    'isPublished': '¿Quieres publicar tu perfil?',

    'settings': 'Configuración',
    'profile': 'Perfil',
    'termsAndConditions': 'Términos y Condiciones',
    'privacyPolicy': 'Política de Privacidad',
    'review': 'Reseña',
    'language': 'Idioma',
    'logout': 'CERRAR SESIÓN',
    'deleteAccount': 'Eliminar cuenta',
    'deleteAccountTitle': 'Eliminar cuenta',
    'deleteAccountSubtitle':
        'Cuéntanos por qué te vas. Tu cuenta y datos se eliminarán permanentemente.',
    'deleteAccountReasonLabel': 'Motivo de baja',
    'deleteAccountReasonHint':
        'Comparte por qué deseas eliminar tu cuenta...',
    'enterDeleteReasonError': 'Introduce un motivo antes de continuar',
    'deleteAccountWarning':
        'Esta acción es permanente. Tu perfil, reservas e historial de sesiones se eliminarán.',
    'deleteAccountConfirmTitle': '¿Eliminar cuenta?',
    'deleteAccountConfirmMessage':
        'Tu cuenta y todos los datos asociados se eliminarán permanentemente. No se puede deshacer.',
    'deleteAccountSuccessTitle': 'Cuenta eliminada',
    'deleteAccountSuccessMessage': 'Tu cuenta ha sido eliminada permanentemente.',

    'editProfile': 'Editar tu perfil',
    'bio': 'Biografía',
    'save': 'Guardar',

    'booking': 'Reserva',
    'tutorDetails': 'Detalles del Tutor',
    'selectSlot': 'Seleccionar Horario',
    'selectTopic': 'Seleccionar Tema',
    'calendarView': 'Vista de calendario',
    'noSlotsAvailable': 'No hay horarios disponibles.',
    'noSlotsAvailableTutor': 'No hay horarios disponibles',
    'showInCalendarView': 'Mostrar en vista de calendario',
    'sessionGoal': 'Objetivo de la Sesión',
    'optionalNote': 'Nota Opcional',
    'optionalNoteHint': 'Dile a tu tutor qué quieres practicar...',
    'bioHint': 'Escribe una breve introducción...',
    'confirmBooking': 'Confirmar reserva',
    'cancellationPolicy':
        'Política de cancelación: Puedes cancelar hasta 30 minutos antes de que comience la sesión.',

    'conversation': 'Conversación',
    'pronunciation': 'Pronunciación',
    'homeworkHelp': 'Ayuda con Tareas',
    'culture': 'Cultura',

    'liveSession': 'Sesión en Vivo',
    'report': 'Reportar',
    'block': 'Bloquear',
    'endSession': 'Terminar Sesión',

    // Tutor side
    'createProfile': 'Crear Perfil',
    'dashboard': 'Panel',
    'availability': 'Disponibilidad',
    'sessionsTab': 'Sesiones',
    'tutorSettings': 'Configuración del Tutor',
    'tutorSessions': 'Sesiones del Tutor',
    'welcomeTutor': 'Bienvenido Tutor',
    'todaySessions': 'Sesiones de Hoy',
    'sessionsToday': 'Sesiones Hoy',
    'upcomingSessions': 'Próximas Sesiones',
    'earnings': 'Ganancias',
    'upcomingBookings': 'Próximas Reservas',
    'date': 'Fecha',
    'time': 'Hora',
    'durationMin': 'Duración (Min)',
    'status': 'Estado',
    'month': 'Mes',
    'availabilityCalendarTitle': 'Disponibilidad',
    'dateWiseAvailabilityData': 'Disponibilidad por Fecha',
    'noDataOnDate': 'No hay datos en esta fecha.',
    'noData': 'Sin datos',
    'availableStatus': 'Disponible',
    'busyStatus': 'Ocupado',
    'topic': 'Tema',
    'seeMore': 'Ver más',
    'seeLess': 'Ver menos',
    'tutorHeadline': 'Titular del Tutor',
    'submit': 'Enviar',
    'viewPublicListingPreview': 'Ver Vista Previa del Perfil Público',
    'addSlot': 'Agregar Horario',
    'editSlot': 'Editar Horario',
    'edit': 'Editar',
    'slotBooked': 'Reservado',
    'weeklyCalendar': 'Calendario Semanal',
    'thirtyMinuteSlots': 'Bloques de 30 Minutos',
    'availableSlotsTitle': 'Horarios Disponibles',
    'addSlotDetails': 'Agregar detalles del horario',
    'topics': 'Temas',
    'startTime': 'Hora de Inicio',
    'endTime': 'Hora de Fin',
    'shortDescription': 'Descripción Corta',
    'shortDescriptionHint': 'Escribe una descripción corta...',
    'selectDate': 'Seleccionar fecha',
    'selectDateError': 'Por favor selecciona una fecha',
    'selectStartTimeError': 'Por favor selecciona la hora de inicio',
    'selectEndTimeError': 'Por favor selecciona la hora de fin',
    'enterShortDescriptionError': 'Por favor ingresa una descripción corta',
    'invalidTimeRangeError':
        'La hora de fin debe ser posterior a la hora de inicio',
    'timeIntervalFiveError':
        'La hora de fin debe ser al menos 5 minutos después de la hora de inicio y en intervalos de 5 minutos',
    'selectTopicError': 'Por favor selecciona un tema',
    'selectSlotError': 'Por favor selecciona un horario',
    'bookingSuccess': 'Reserva confirmada',
    'cancelSessionConfirmTitle': 'Cancelar Sesión',
    'cancelSessionConfirmMessage':
        '¿Estás seguro de que quieres cancelar esta sesión?',
    'reportSpam': 'Reportar / Reseña',
    'reportSessionTitle': 'Reportar esta sesión',
    'message': 'Mensaje',
    'chat': 'Chat',
    'chatWithTutor': 'Chat con tutor',
    'chatWithStudent': 'Chat con estudiante',
    'typeMessage': 'Escribe un mensaje...',
    'chatEmptyTitle': 'Inicia la conversación',
    'chatEmptySubtitle':
        'Envía un mensaje a {name} para coordinar tu sesión.',
    'chatInboxEmptyTitle': 'Aún no hay chats',
    'chatInboxEmptySubtitle':
        'Cuando los estudiantes te escriban, las conversaciones aparecerán aquí.',
    'chatNoMessagesYet': 'Aún no hay mensajes',
    'notifications': 'Notificaciones',
    'notificationsEmpty': 'No hay notificaciones.',
    'notificationSessionStart': 'Inicio de sesión',
    'notificationSessionCancel': 'Sesión cancelada',
    'reportList': 'Lista de Reportes / Reseñas',
    'reportListEmpty': 'No se encontraron reportes.',
    'reportReason': 'Motivo',
    'reportSessionId': 'ID de Sesión',
    'reportedOn': 'Reportado el',
    'reportSessionReasonHint':
        'Describe lo que pasó. Tu reporte ayuda a mantener la comunidad segura.',
    'selectReportTypeHint': 'Selecciona tipo',
    'reportSessionTypeEmptyError': 'Por favor selecciona Reporte o Reseña.',
    'reportSessionReasonEmptyError':
        'Por favor ingresa un motivo para tu reporte.',
    'sessionRatingLabel': 'Califica esta sesión',
    'reportSessionRatingRequired':
        'Por favor elige una calificación con estrellas para tu reseña.',
    'reportSessionSuccessFallback': 'Reporte enviado correctamente',
    'createTutorProfile': 'Crear Perfil de Tutor',
    'publishedListingPreview': 'Vista Previa del Perfil Publicado',
    'publish': 'Publicar',
    'unpublish': 'Despublicar',

    // Extra languages for dropdowns
    'spanish': 'Español',
    'japanese': 'Japonés',
    'other': 'Otro',

    'noInternetMessage':
        'Sin conexión a internet. Revisa el Wi‑Fi o los datos móviles.',
    'locationServicesDisabled':
        'Los servicios de ubicación están desactivados.',
    'locationPermissionsDenied': 'Los permisos de ubicación fueron denegados.',
    'locationPermissionsPermanentlyDenied':
        'El permiso de ubicación ha sido denegado permanentemente. Para unirte a la sesión, habilita el acceso a la ubicación en la configuración de tu dispositivo.',
  };

  static String text(AppLanguage language, String key) {
    return language == AppLanguage.korean
        ? _ko[key] ?? key
        : language == AppLanguage.spanish
        ? _es[key] ?? key
        : _en[key] ?? key;
  }
}
